Revert "Register IpClient as OffloadEngine when APF supports mDNS offload"
This reverts commit ec05c93dbf647eb3d0b5d55bedc80c6dddb8f6cb.

Reason for revert: The TH+1 in the original CL seems a false positive. This CL cause the following test conflict.

[ 92% 486/528 27s remaining] //packages/modules/NetworkStack/tests/unit:NetworkStackTests javac [common]
FAILED: out/soong/.intermediates/packages/modules/NetworkStack/tests/unit/NetworkStackTests/android_common/javac/NetworkStackTests.jar out/soong/.intermediates/packages/modules/NetworkStack/tests/unit/NetworkStackTests/android_common/javac/anno.srcjar
packages/modules/NetworkStack/tests/unit/src/android/net/ip/IpClientTest.java:1088: error: method maybeCreateApfFilter in class Dependencies cannot be applied to given types;
        doReturn(mApfFilter).when(mDependencies).maybeCreateApfFilter(any(), any(), any(), any(),
                                                ^
  required: Handler,Context,ApfConfiguration,InterfaceParams,IpClientCallbacksWrapper,NetworkQuirkMetrics,boolean
  found:    Object,Object,Object,Object,Object,boolean
  reason: actual and formal argument lists differ in length
packages/modules/NetworkStack/tests/unit/src/android/net/ip/IpClientTest.java:1089: error: incompatible types: boolean cannot be converted to NetworkQuirkMetrics
                any(), anyBoolean());
                                 ^
packages/modules/NetworkStack/tests/unit/src/android/net/ip/IpClientTest.java:1120: error: method maybeCreateApfFilter in class Dependencies cannot be applied to given types;
        doReturn(mApfFilter).when(mDependencies).maybeCreateApfFilter(any(), any(), any(), any(),
                                                ^
  required: Handler,Context,ApfConfiguration,InterfaceParams,IpClientCallbacksWrapper,NetworkQuirkMetrics,boolean
  found:    Object,Object,Object,Object,Object,boolean
  reason: actual and formal argument lists differ in length
packages/modules/NetworkStack/tests/unit/src/android/net/ip/IpClientTest.java:1121: error: incompatible types: boolean cannot be converted to NetworkQuirkMetrics
                any(), anyBoolean());
(cherry picked from https://android-review.googlesource.com/q/commit:5f75615175e6674fb0e146165dfa5dfa3346bc0f)
Merged-In: If71c0a529cf56150cb0c7fd26720f9d761c2534b
Change-Id: If71c0a529cf56150cb0c7fd26720f9d761c2534b